export const ACCOUNTS_GETALL_REQUEST = 'ACCOUNTS_GETALL_REQUEST'
export const ACCOUNTS_GETALL_SUCCESS = 'ACCOUNTS_GETALL_SUCCESS'
export const ACCOUNTS_GETALL_FAILURE = 'ACCOUNTS_GETALL_FAILURE'
export const ACCOUNTS_GETUSERACCOUNTS = 'ACCOUNTS_GETUSERACCOUNTS'

export const PAYMENTS_GETALL_REQUEST = 'PAYMENTS_GETALL_REQUEST'
export const PAYMENTS_GETALL_SUCCESS = 'PAYMENTS_GETALL_SUCCESS'
export const PAYMENTS_GETALL_FAILURE = 'PAYMENTS_GETALL_FAILURE'
export const PAYMENTS_GETUSERPAYMENTS = 'PAYMENTS_GETUSERPAYMENTS'

export const TRANSFERS_GETALL_REQUEST = 'TRANSFERS_GETALL_REQUEST'
export const TRANSFERS_GETALL_SUCCESS = 'TRANSFERS_GETALL_SUCCESS'
export const TRANSFERS_GETALL_FAILURE = 'TRANSFERS_GETALL_FAILURE'
export const TRANSFERS_GETUSERTRANSFERS = 'TRANSFERS_GETUSERTRANSFERS'
