export const ACCOUNTS_GETALL_REQUEST = 'ACCOUNTS_GETALL_REQUEST'
export const ACCOUNTS_GETALL_SUCCESS = 'ACCOUNTS_GETALL_SUCCESS'
export const ACCOUNTS_GETALL_FAILURE = 'ACCOUNTS_GETALL_FAILURE'
export const ACCOUNTS_GETUSERACCOUNTS = 'ACCOUNTS_GETUSERACCOUNTS'

export const PAYMENTS_GETALL_REQUEST = 'PAYMENTS_GETALL_REQUEST'
export const PAYMENTS_GETALL_SUCCESS = 'PAYMENTS_GETALL_SUCCESS'
export const PAYMENTS_GETALL_FAILURE = 'PAYMENTS_GETALL_FAILURE'
export const PAYMENTS_GETUSERPAYMENTS = 'PAYMENTS_GETUSERPAYMENTS'

export const TRANSFERS_GETALL_REQUEST = 'TRANSFERS_GETALL_REQUEST'
export const TRANSFERS_GETALL_SUCCESS = 'TRANSFERS_GETALL_SUCCESS'
export const TRANSFERS_GETALL_FAILURE = 'TRANSFERS_GETALL_FAILURE'
export const TRANSFERS_GETUSERTRANSFERS = 'TRANSFERS_GETUSERTRANSFERS'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const CREATE_USER_ACCOUNT_REQUEST = 'CREATE_USER_ACCOUNT_REQUEST'
export const CREATE_USER_ACCOUNT_SUCCESS = 'CREATE_USER_ACCOUNT_SUCCESS'
export const CREATE_USER_ACCOUNT_FAILURE = 'CREATE_USER_ACCOUNT_FAILURE'

export const PAY_PAYMENT_REQUEST = 'PAY_PAYMENT_REQUEST'
export const PAY_PAYMENT_SUCCESS = 'PAY_PAYMENT_SUCCESS'
export const PAY_PAYMENT_FAILURE = 'PAY_PAYMENT_FAILURE'

export const TRANSFERS_REQUEST = 'TRANSFERS_REQUEST'
export const TRANSFERS_SUCCESS = 'TRANSFERS_SUCCESS'
export const TRANSFERS_FAILURE = 'TRANSFERS_FAILURE'

export const CREATE_BANKACCOUNT_REQUEST = 'CREATE_BANKACCOUNT_REQUEST'
export const CREATE_BANKACCOUNT_SUCCESS = 'CREATE_BANKACCOUNT_SUCCESS'
export const CREATE_BANKACCOUNT_FAILURE = 'CREATE_BANKACCOUNT_FAILURE'

export const CLIENTS_REQUEST = 'CLIENTS_REQUEST'
export const CLIENTS_SUCCESS = 'CLIENTS_SUCCESS'
export const CLIENTS_FAILURE = 'CLIENTS_FAILURE'

export const CLIENT_BY_SOCIALNUMBER_REQUEST = 'CLIENT_BY_SOCIALNUMBER_REQUEST'
export const CLIENT_BY_SOCIALNUMBER_SUCCESS = 'CLIENT_BY_SOCIALNUMBER_SUCCESS'
export const CLIENT_BY_SOCIALNUMBER_FAILURE = 'CLIENT_BY_SOCIALNUMBER_FAILURE'

export const CREATE_CLIENT_REQUEST = 'CREATE_CLIENT_REQUEST'
export const CREATE_CLIENT_SUCCESS = 'CREATE_CLIENT_SUCCESS'
export const CREATE_CLIENT_FAILURE = 'CREATE_CLIENT_FAILURE'

export const PROVIDERS_REQUEST = 'PROVIDERS_REQUEST'
export const PROVIDERS_SUCCESS = 'PROVIDERS_SUCCESS'
export const PROVIDERS_FAILURE = 'PROVIDERS_FAILURE'

export const CREATE_PROVIDER_REQUEST = 'CREATE_PROVIDER_REQUEST'
export const CREATE_PROVIDER_SUCCESS = 'CREATE_PROVIDER_SUCCESS'
export const CREATE_PROVIDER_FAILURE = 'CREATE_PROVIDER_FAILURE'

export const CREATE_UPDATE_PAYMENT_REQUEST = 'CREATE_UPDATE_PAYMENT_REQUEST'
export const CREATE_UPDATE_PAYMENT_SUCCESS = 'CREATE_UPDATE_PAYMENT_SUCCESS'
export const CREATE_UPDATE_PAYMENT_FAILURE = 'CREATE_UPDATE_PAYMENT_FAILURE'
