export const ACCOUNTS_GETALL_REQUEST = 'ACCOUNTS_GETALL_REQUEST'
export const ACCOUNTS_GETALL_SUCCESS = 'ACCOUNTS_GETALL_SUCCESS'
export const ACCOUNTS_GETALL_FAILURE = 'ACCOUNTS_GETALL_FAILURE'
export const ACCOUNTS_GETUSERACCOUNTS = 'ACCOUNTS_GETUSERACCOUNTS'

export const PAYMENTS_GETALL_REQUEST = 'PAYMENTS_GETALL_REQUEST'
export const PAYMENTS_GETALL_SUCCESS = 'PAYMENTS_GETALL_SUCCESS'
export const PAYMENTS_GETALL_FAILURE = 'PAYMENTS_GETALL_FAILURE'
export const PAYMENTS_GETUSERPAYMENTS = 'PAYMENTS_GETUSERPAYMENTS'

export const TRANSFERS_GETALL_REQUEST = 'TRANSFERS_GETALL_REQUEST'
export const TRANSFERS_GETALL_SUCCESS = 'TRANSFERS_GETALL_SUCCESS'
export const TRANSFERS_GETALL_FAILURE = 'TRANSFERS_GETALL_FAILURE'
export const TRANSFERS_GETUSERTRANSFERS = 'TRANSFERS_GETUSERTRANSFERS'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const CREATE_USER_ACCOUNT_REQUEST = 'CREATE_USER_ACCOUNT_REQUEST'
export const CREATE_USER_ACCOUNT_SUCCESS = 'CREATE_USER_ACCOUNT_SUCCESS'
export const CREATE_USER_ACCOUNT_FAILURE = 'CREATE_USER_ACCOUNT_FAILURE'

export const PAY_PAYMENT_REQUEST = 'PAY_PAYMENT_REQUEST'
export const PAY_PAYMENT_SUCCESS = 'PAY_PAYMENT_SUCCESS'
export const PAY_PAYMENT_FAILURE = 'PAY_PAYMENT_FAILURE'
